### ISSUE TITLE
Is this code updated with the latest release (1.3.1)?

### ISSUE THREAD

**Issue by ghost** [davidepianca98/rom_porter#2]
I'm looking to port your code into a shell script for Mac OS X or Linux compatibility. Just wanted to know. Get back to me as soon as possible. Thanks.

**Comment by davidepianca98** [comment]
No latest pull request isn't published on xda. So this is actually 1.3.2 version and on xda there is 1.3.1. This prohect is abandoned. If you want to continue it you are free to do it but remember credits.

**Comment by ghost** [comment]
That's fine. I am interested in continuing the project and just wanted to know. Thanks for the information.

I also wanted to know: on what devices has this been tested on? I haven't had the time to read all 50 pages on XDA and just wanted to know if there are any present issues that I can work with. I forked your repository, and you can check out the changes I make there. The help is appreciated.

**Comment by davidepianca98** [comment]
I don't know on which devices it has been tested but it worked many times. Actually issues are with aroma installer port and in fix tool the HTC graphical issues fix
