### ISSUE TITLE
Not clear instuctions

### ISSUE THREAD

**Issue by ghost** [davidepianca98/rom_porter#3]
Copy every extra folder or file from \Port-Rom\port\system to  \Base-Rom\base\system

This explains nothing, what kind of extra folders? Isn't the tool supposed to copy them. Give me an example of folders?
framework? ( doesnt the tool copy the framework? )

**Comment by davidepianca98** [comment]
It means that there may be some folder that usually doesn't exist in other roms. This happens only in stock based roms sometimes. For example /system/romtools may exist in port but the tool won't copy it because usually it isn't there
